name: work_it_project
description: Login UI

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  flutter_spinkit: ^4.1.2+1
  provider: ^4.3.2+2
  local_auth: ^0.6.3+4
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2

  scoped_model: ^1.0.1
  path_provider: ^0.5.0+1
  json_annotation: ^2.0.0
  sqflite: ^1.1.0
  flutter_colorpicker: ^0.2.1
  intl: ^0.16.1
  flutter_markdown: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.2

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/img/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
